{% set name = "pysmi" %}
{% set version = "1.5.0" %}
{% set sha256 = "e42bcd3961de71d58186f7a7fa6adac133701ae74cd19e6376289d89593b0af2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Make-importlib-imports-explicit.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6,<4.0
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=3.6,<4.0
    - ply <4.0,>=3.11
    - jinja2 <4.0.0,>=3.1.3
    - requests <3.0.0,>=2.26.0

test:
  imports:
    - pysmi
    - pysmi.borrower
    - pysmi.codegen
    - pysmi.lexer
    - pysmi.parser
    - pysmi.reader
    - pysmi.searcher
    - pysmi.writer

about:
  home: http:/pysmi.sf.net
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: SNMP SMI/MIB Parser
  description: 'A pure-Python implementation of SNMP/SMI MIB parsing and conversion library.'
  doc_url: http://snmplabs.com/pysmi/#documentation
  dev_url: https://github.com/etingof/pysmi

extra:
  recipe-maintainers:
    - nehaljwani
